server:
  port: 8080

spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database: POSTGRESQL
  datasource:
    platform: postgres
    database: kube_deployer
    host: localhost
    port: 5432
    url: "jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}"
    username: test
    password: test
  security:
    jwt:
      token:
        secret-key: change-me
        expiration-time: 600_000 # in milliseconds. 10 minutes token expiration by default
